# Лабораторная работа 1. Введение в машинное обучение. Обучение с учителем. Задача регрессии

<b>Традиционное предупреждение для всех лабораторных работ:</b> перед обучением моделей необходимо выполнить предварительную обработку данных, которая <b>обязательно</b> включает в себя:
- заполнение пропущенных значений (рекомедуется логика заполнения пропусков на основе типа данных, которая использовалась в РГР по Практикуму);
- преобразование категориальных признаков в числовые (используйте one-hot кодирование или map; используйте знания с Практикума).

Предобработка может включать в себя другие действия, но выполнение описанных выше действий обязательно.

Сделайте это один раз и сохраните в отдельный csv файл, а потом его используйте.

<b>Выполните следующие задания:</b>
- загрузите датасет для регрессии, выделите целевой признак и предикторы, разбейте данные на обучающую и тестовую выборку;
- решите задачу регрессии на ваших данных с использованием моделей sklearn (линейная регрессия + L1, L2), для моделей с регуляризациями подберите гиперпараметр;
- решите задачу регрессии на ваших данных с использованием моделей sklearn (полиномиальная регрессия + L1, L2), для моделей с регуляризациями подберите гиперпараметр;
- вычислите значения метрик $R^2$, MAE, MSE, RMSE, MAPE для всех обученных моделей; выберите лучшую модель;
- самостоятельно реализуйте (желательно в виде класса) модель линейной регрессии с регуляризацией (можете выбрать L1 или L2);
- самостоятельно реализуйте вычисление всех используемых метрик (в виде функций, принимающих два аргумента);
- обучите вашу модель линейной регрессии на ваших данных; оцените качество с помощью реализованных вами метрик.

In [396]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt

In [397]:
data= pd.read_csv("../data/trip_duration_task.csv")
data.drop(['id','pickup_datetime', 'dropoff_datetime', 'vendor_id', 'passenger_count' ], axis=1, inplace=True)
data.drop_duplicates(inplace=True)
data.dropna(inplace=True)
data

pickup_longitude  pickup_latitude  dropoff_longitude  \
0             -73.953918        40.778873         -73.963875   
1             -73.988312        40.731743         -73.994751   
2             -73.997314        40.721458         -73.948029   
3             -73.961670        40.759720         -73.956779   
4             -74.017120        40.708469         -73.988182   
...                  ...              ...                ...   
729317        -73.965919        40.789780         -73.952637   
729318        -73.996666        40.737434         -74.001320   
729319        -73.997849        40.761696         -74.001488   
729320        -74.006706        40.708244         -74.013550   
729321        -74.003342        40.743839         -73.945847   

        dropoff_latitude  trip_duration  
0              40.771164            400  
1              40.694931           1100  
2              40.774918           1635  
3              40.780628           1141  
4              40.740631            848  
...                  ...            ...  
729317         40.789181            296  
729318         40.731911            315  
729319         40.741207            673  
729320         40.713814            447  
729321         40.712841           1224  

[727475 rows x 5 columns]

In [398]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 727475 entries, 0 to 729321
Data columns (total 5 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   pickup_longitude   727475 non-null  float64
 1   pickup_latitude    727475 non-null  float64
 2   dropoff_longitude  727475 non-null  float64
 3   dropoff_latitude   727475 non-null  float64
 4   trip_duration      727475 non-null  int64  
dtypes: float64(4), int64(1)
memory usage: 33.3 MB


Предобработка данных

1) Убрал строки с null-value в столбце "vendor_id"
2) Заполнил строки с null-value в столбце "pickup_latitude"

In [399]:
y = data['trip_duration']
X = data.drop(['trip_duration'], axis=1)


In [400]:
y

0          400
1         1100
2         1635
3         1141
4          848
          ... 
729317     296
729318     315
729319     673
729320     447
729321    1224
Name: trip_duration, Length: 727475, dtype: int64

In [401]:
X

pickup_longitude  pickup_latitude  dropoff_longitude  dropoff_latitude
0             -73.953918        40.778873         -73.963875         40.771164
1             -73.988312        40.731743         -73.994751         40.694931
2             -73.997314        40.721458         -73.948029         40.774918
3             -73.961670        40.759720         -73.956779         40.780628
4             -74.017120        40.708469         -73.988182         40.740631
...                  ...              ...                ...               ...
729317        -73.965919        40.789780         -73.952637         40.789181
729318        -73.996666        40.737434         -74.001320         40.731911
729319        -73.997849        40.761696         -74.001488         40.741207
729320        -74.006706        40.708244         -74.013550         40.713814
729321        -74.003342        40.743839         -73.945847         40.712841

[727475 rows x 4 columns]

In [402]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [403]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((581980, 4), (581980,), (145495, 4), (145495,))

In [404]:
lr = LinearRegression().fit(X_train, y_train)

In [405]:
lr.predict(X_test)

array([1087.15593751,  829.00583492,  875.16839257, ...,  943.30398294,
        920.24129988, 1020.56485141])

In [406]:
y_pred = lr.predict(X_test)
y_pred.shape

(145495,)

In [407]:
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {lr.score(X_test, y_test)}')
print(f'R^2: {lr.score(X, y)}')

MAE: 582.486370784492
MSE: 8813885.966800643
RMSE: 2968.8189515025406
MAPE: 1.2803248068630135
R^2: 0.005804991377032054
R^2: 0.003085614014929572


In [408]:
len(lr.coef_)
lr.coef_

array([ 2568.73992558, -3496.61096807,  -813.7965921 , -1652.75306596])

In [409]:
ridge = Ridge(alpha=0.9).fit(X_train, y_train)
y_pred = ridge.predict(X_test)
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {ridge.score(X_test, y_test)}')
ridge.coef_

MAE: 582.4913689540366
MSE: 8813888.855788473
RMSE: 2968.8194380575715
MAPE: 1.2803144254976069
R^2: 0.005804665502918138


array([ 2566.40110921, -3492.29143264,  -811.92876302, -1652.84447337])

In [410]:
parameters = {'alpha': np.arange(0, 1, 0.1)}
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_train, y_train)
ridge_optimal.best_params_

{'alpha': 0.9}