In [6]:
import sys
import pandas as pd
sys.path.insert(1, '/Users/max/projects/machine-learning-labs/tensorflow')
from mytensorflow import *
import tensorflow as tf
import numpy as np

import tensorflow_datasets as tfdt
import pandas as pd
import numpy as np
import os
from keras.layers import Dense, Flatten, Reshape, Input, InputLayer
from keras.models import Sequential, Model

from  matplotlib import pyplot as plt
import random
import tensorflow as tf
import os
from PIL import Image
from tensorflow.python.ops.numpy_ops import np_config
np_config.enable_numpy_behavior()
from tensorflow import keras
import matplotlib.image as mpimg
%matplotlib inline

In [7]:
IMG_WIDTH=200
IMG_HEIGHT=200
img_folder=r'/Users/max/projects/machine-learning-labs/data/catsdogs'

In [8]:
import os
import numpy_utils as np_utils
def create_dataset_PIL(img_folder):
    
    img_data_array=[]
    class_name=[]
    for dir1 in os.listdir(img_folder):
        for file in os.listdir(os.path.join(img_folder, dir1)):
       
            image_path= os.path.join(img_folder, dir1,  file)
            image= np.array(Image.open(image_path))
            image= np.resize(image,(IMG_HEIGHT,IMG_WIDTH,3))
            image = image.astype('float32')
            image /= 255  
            img_data_array.append(image)
            class_name.append(dir1)
            
    return img_data_array , class_name

In [9]:
PIL_img_data, class_name=create_dataset_PIL(img_folder)
len(PIL_img_data)
target_dict={k: v for v, k in enumerate(np.unique(class_name))}
target_val=  [target_dict[class_name[i]] for i in range(len(class_name))]

In [10]:
x = np.array(PIL_img_data)
y = np.array(target_val)
print(y[:1000:].shape)

(1000,)


In [13]:
net = Network()
net.add(ConvolutionalLayer((200,200,3), (3,3), 1))
net.add (MaxPoolingLayer((3,3),2))
net.add(FlattenLayer())
net.add(FCLayer(39204, 1))
net.add(ActivationLayer(Sigmoid.callFunction, Sigmoid.callDerivative))
net.compile(BinaryCrossEntropy.fun, BinaryCrossEntropy.derivative)
net.fit(x[::20], y[::20], epochs=10, learning_rate=0.001)

[[[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]]
[[[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]]
[[[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]]
[[[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]]
[[[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]]
[[[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]]
[[[-0.86362181]
  [-0.86362181]
  [-0.86362181]]

 [[-0.86362181]
  [-0.86362181]
  [-0.86362181]]



IndexError: index 2 is out of bounds for axis 0 with size 2

In [ ]:
img = tf.keras.preprocessing.image.load_img(
    "../data/catsdogs/cats/0.jpg", target_size=(200, 200)
)
img_array = tf.keras.preprocessing.image.img_to_array(img)
img_array = tf.expand_dims(img_array, 0)

predictions = net.predict(PIL_img_data[::10])
predictions

[array([0.97968798]),
 array([0.99469695]),
 array([4.29526618e-06]),
 array([0.99469695]),
 array([0.99998472]),
 array([1.]),
 array([0.99469695]),
 array([0.99469695]),
 array([0.99469695]),
 array([0.95719946]),
 array([0.99469695]),
 array([0.99469695]),
 array([0.99469695]),
 array([0.99999467]),
 array([0.99469695]),
 array([0.99658559]),
 array([0.99469695]),
 array([0.99469695]),
 array([0.99469695]),
 array([0.00748332]),
 array([0.99469695]),
 array([0.9901345]),
 array([0.99935446]),
 array([1.]),
 array([0.99986409]),
 array([0.99999969]),
 array([0.08353509]),
 array([0.99999998]),
 array([0.99469695]),
 array([1.]),
 array([0.99998]),
 array([0.99469695]),
 array([0.77167306]),
 array([0.92764328]),
 array([0.99469695]),
 array([0.99119397]),
 array([0.99977648]),
 array([0.17453209]),
 array([0.99469695]),
 array([0.11725765]),
 array([0.99469695]),
 array([0.99469695]),
 array([0.99752402]),
 array([1.]),
 array([0.52725388]),
 array([0.99055995]),
 array([0.99421531])

In [ ]:
for y_pred, y_true in zip(predictions, class_name[::10]):
    print(f"pred: {(y_pred)}, true: {y_true}")

NameError: name 'predictions' is not defined

In [ ]:
data = np.array([[1,9,8,4],
        [4,8,6,7],
        [4,0,5,9],
        [7,3,5,4]])

In [ ]:
data.shape

(4, 4)

In [16]:
max = MaxPoolingLayer((2,2), 3)
res = max.forward_propagation(data)
res2 = max.backward_propagation(res, 0.1)
res2

[[1 9]
 [4 8]]
[[4]
 [7]]


IndexError: index 1 is out of bounds for axis 0 with size 1