In [38]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [39]:
class MetricsClassification:
    @staticmethod
    def accuracy(y_test, y_pred):
        y_true, predictions = np.array(y_test), np.array(y_pred)
        return len([x for x, y  in zip(y_true, predictions) if x  == y])/len(y_true)
    
    @staticmethod
    def confusion_matrix(y_test, y_pred):
        y_true, predictions = np.array(y_test), np.array(y_pred)
        TP = FP =TN =FN = 0
        for test, pred in zip(y_true, predictions):
            if (test == 1 and pred == 1):
                TP += 1 
            elif (test == 0 and pred == 0):
                TN += 1
            elif (test == 1 and pred == 0):
                FN += 1
            elif (test == 0 and pred == 1):
                FP += 1
        return [[TP, FP],
                         [FN, TN]]
    @staticmethod
    def precision( y_test, y_pred):
        matrix = MetricsClassification.confusion_matrix(y_test, y_pred)
        TP = matrix[0][0]
        FP = matrix[0][1]
        return TP/(TP + FP)
    @staticmethod
    def recall(y_test, y_pred):
        matrix = MetricsClassification.confusion_matrix(y_test, y_pred)
        TP = matrix[0][0]
        FN = matrix[1][0]
        return TP/(TP + FN)
    
    @staticmethod
    def f_score(y_test, y_pred):
        recall_score = MetricsClassification.recall(y_test, y_pred)
        precision_score = MetricsClassification.precision(y_test, y_pred)
        return 2*(recall_score * precision_score)/ (recall_score+precision_score)






In [42]:
a1 = np.random.randint(2, size=10)
a2 = np.random.randint(2, size=10)
print(a1)
print(a2)
print(MetricsClassification.accuracy(a1, a2))
print(accuracy_score(a1, a2))
print(MetricsClassification.confusion_matrix(a1, a2))
print(confusion_matrix(a1, a2))

print(MetricsClassification.precision(a1, a2))
print(precision_score(a1, a2))
print(MetricsClassification.recall(a1, a2))
print(recall_score(a1, a2))
print(MetricsClassification.f_score(a1, a2))
print(f1_score(a1, a2))

[1 0 0 0 0 0 1 1 1 0]
[0 1 0 1 0 1 0 0 1 1]
0.3
0.3
[[1, 4], [3, 2]]
[[2 4]
 [3 1]]
0.2
0.2
0.25
0.25
0.22222222222222224
0.22222222222222224
