In [32]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split

In [16]:
class MetricsClassification:
    @staticmethod
    def accuracy(y_test, y_pred):
        y_true, predictions = np.array(y_test), np.array(y_pred)
        return len([x for x, y  in zip(y_true, predictions) if x  == y])/len(y_true)
    
    @staticmethod
    def confusion_matrix(y_test, y_pred):
        y_true, predictions = np.array(y_test), np.array(y_pred)
        TP = FP =TN =FN = 0
        for test, pred in zip(y_true, predictions):
            if (test == 1 and pred == 1):
                TP += 1 
            elif (test == 0 and pred == 0):
                TN += 1
            elif (test == 1 and pred == 0):
                FN += 1
            elif (test == 0 and pred == 1):
                FP += 1
        return [[TP, FP],
                         [FN, TN]]
    @staticmethod
    def precision( y_test, y_pred):
        matrix = MetricsClassification.confusion_matrix(y_test, y_pred)
        TP = matrix[0][0]
        FP = matrix[0][1]
        return TP/(TP + FP)
    @staticmethod
    def recall(y_test, y_pred):
        matrix = MetricsClassification.confusion_matrix(y_test, y_pred)
        TP = matrix[0][0]
        FN = matrix[1][0]
        return TP/(TP + FN)
    
    @staticmethod
    def f_score(y_test, y_pred):
        recall_score = MetricsClassification.recall(y_test, y_pred)
        precision_score = MetricsClassification.precision(y_test, y_pred)
        return 2*(recall_score * precision_score)/ (recall_score+precision_score)






In [17]:
a1 = np.random.randint(2, size=10)
a2 = np.random.randint(2, size=10)
print(a1)
print(a2)
print(MetricsClassification.accuracy(a1, a2))
print(accuracy_score(a1, a2))
print(MetricsClassification.confusion_matrix(a1, a2))
print(confusion_matrix(a1, a2))

print(MetricsClassification.precision(a1, a2))
print(precision_score(a1, a2))
print(MetricsClassification.recall(a1, a2))
print(recall_score(a1, a2))
print(MetricsClassification.f_score(a1, a2))
print(f1_score(a1, a2))

[0 0 0 0 0 1 0 0 1 1]
[1 1 0 0 0 1 1 1 0 1]
0.5
0.5
[[2, 4], [1, 3]]
[[3 4]
 [1 2]]
0.3333333333333333
0.3333333333333333
0.6666666666666666
0.6666666666666666
0.4444444444444444
0.4444444444444444


In [18]:
def euclidean_distance(x1,x2):
    return np.sqrt(sum((x1-x2)**2))


In [19]:
def get_distances_(x_test, x_train):
        distances = []
        for x in x_train:
            distance = euclidean_distance(x_test, x)
            distances.append(distance)
        return distances

In [29]:
def most_common(list):
    return max(set(list), key=list.count)

In [21]:
point1 = np.array((0,0,0))
point2 = np.array((3,3,3))
print(euclidean_distance(point1,point2))

5.196152422706632


In [22]:
class KNeighborsClassifier:
    def __init__( self, k) :
        self.k = k
    def fit(self, x_train, y_train):
        self.X_train = x_train
        self.y_train = y_train
        return self
    
    def predict(self, X_test):
        neighbors = []
        for x in X_test:
            distances = get_distances_(x, self.X_train)
            y_sorted = [y for _, y in sorted(zip(distances, self.y_train))][:self.k]
            neighbors.append(y_sorted)
        return list(map(most_common, neighbors))

In [23]:
data = pd.read_csv("../data/csgo_task_m.csv")

In [24]:
X = data.values
y = data["bomb_planted"].values

In [25]:
underSampler = RandomUnderSampler(random_state=42)
X_under_sample, y_under_sample = underSampler.fit_resample(X,y)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X_under_sample, y_under_sample, test_size=0.2, random_state=4)

In [30]:
knn = KNeighborsClassifier(k=5)
model = knn.fit(X_train, y_train)
predictions = model.predict(X_test)



In [28]:
predictions

[[(1, 3), (0, 2)],
 [(0, 3), (1, 2)],
 [(1, 5)],
 [(0, 3), (1, 2)],
 [(1, 3), (0, 2)],
 [(0, 3), (1, 2)],
 [(1, 5)],
 [(0, 3), (1, 2)],
 [(0, 3), (1, 2)],
 [(1, 3), (0, 2)],
 [(0, 4), (1, 1)],
 [(0, 3), (1, 2)],
 [(0, 3), (1, 2)],
 [(1, 3), (0, 2)],
 [(0, 5)],
 [(1, 5)],
 [(0, 3), (1, 2)],
 [(0, 4), (1, 1)],
 [(0, 4), (1, 1)],
 [(0, 4), (1, 1)],
 [(1, 5)],
 [(1, 5)],
 [(0, 3), (1, 2)],
 [(0, 5)],
 [(0, 5)],
 [(0, 3), (1, 2)],
 [(1, 5)],
 [(1, 5)],
 [(1, 5)],
 [(0, 3), (1, 2)],
 [(0, 3), (1, 2)],
 [(1, 5)],
 [(0, 3), (1, 2)],
 [(0, 3), (1, 2)],
 [(0, 4), (1, 1)],
 [(1, 3), (0, 2)],
 [(0, 4), (1, 1)],
 [(1, 4), (0, 1)],
 [(0, 4), (1, 1)],
 [(1, 4), (0, 1)],
 [(1, 3), (0, 2)],
 [(0, 3), (1, 2)],
 [(1, 4), (0, 1)],
 [(0, 5)],
 [(1, 3), (0, 2)],
 [(0, 3), (1, 2)],
 [(1, 3), (0, 2)],
 [(1, 5)],
 [(0, 3), (1, 2)],
 [(1, 4), (0, 1)],
 [(0, 4), (1, 1)],
 [(0, 4), (1, 1)],
 [(0, 4), (1, 1)],
 [(0, 4), (1, 1)],
 [(0, 3), (1, 2)],
 [(1, 3), (0, 2)],
 [(0, 4), (1, 1)],
 [(1, 3), (0, 2)],
 [(1, 3), 

In [31]:
print(MetricsClassification.accuracy(y_test, predictions))
print(accuracy_score(y_test, predictions))
print(MetricsClassification.confusion_matrix(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(MetricsClassification.precision(y_test, predictions))
print(precision_score(y_test, predictions))
print(MetricsClassification.recall(y_test, predictions))
print(recall_score(y_test, predictions))
print(MetricsClassification.f_score(y_test, predictions))
print(f1_score(y_test, predictions))

0.6869203104296802
0.6869203104296802
[[1652, 719], [935, 1977]]
[[1977  719]
 [ 935 1652]]
0.6967524251370729
0.6967524251370729
0.638577502899111
0.638577502899111
0.6663977410246067
0.6663977410246067
