In [31]:
import numpy as np
def corelation2d(in1 = np.array((3,3)), in2 = np.array((3,3)), mode = "valid", stride = 1):
    output = np.array(in2.shape)
    y = 0
    n = len(in1)
    m = len(in2)
    index1 = 0
    index2 = m
    index3 = 0
    index4 = m

    while(index2 <=n):
        while(index4 <= n):
            y = 0
            submatrix = in1[index1:index2, index3:index4]
            y += np.sum(np.multiply(submatrix, in2))
            print(y)
            print(submatrix)
            index3 +=stride
            index4 +=stride
        index1 += stride
        index2 += stride
        index3 = 0
        index4  = m
        
        
       

def main():
    in1 = np.array([[1,6,2],
           [5,3,1],
           [7,0,4]])
    in2 = np.array([[1,2],
           [-1,0]])
    corelation2d(in1, in2)





In [32]:
main()

8
[[1 6]
 [5 3]]
7
[[6 2]
 [3 1]]
4
[[5 3]
 [7 0]]
5
[[3 1]
 [0 4]]
