In [112]:
from cross_corelation import *
from scipy import signal
def main():
    in1 = np.array([[1, 2], [4, 5],])
    kernel = np.array([[1, 0], [1, 0]])


    
    print(correlate2d(in1, kernel, "full"))

    print("------")
    print(signal.correlate2d(in1, kernel, "full"))

    print(correlate2d(in1, kernel, "valid"))

    print("------")
    print(signal.correlate2d(in1, kernel, "valid"))

    print(correlate2d(in1, kernel, "same"))

    print("------")
    print(signal.correlate2d(in1, kernel, "same"))


# def correlate2d(signal, kernel):
#     signal_height, signal_width = signal.shape
#     kernel_height, kernel_width = kernel.shape

#     # Calculate padding sizes
#     pad_height = kernel_height - 1
#     pad_width = kernel_width - 1

#     # Pad the signal
#     padded_signal = np.pad(signal, ((pad_height, pad_height), (pad_width, pad_width)), mode='constant')

#     # Initialize the output array
#     output_height = signal_height + 2 * pad_height
#     output_width = signal_width + 2 * pad_width
#     output = np.zeros((output_height, output_width))

#     # Perform cross-correlation
#     for i in range(output_height):
#         for j in range(output_width):
#             output[i, j] = np.sum(padded_signal[i:i+kernel_height, j:j+kernel_width] * kernel)

#     return output

# Example usage

In [113]:
def correlate2d(in1: np.ndarray, in2: np.ndarray, mode="valid", stride=1):
    n = len(in1)
    m = len(in2)
    result = []
    result_shape = 0
    if (mode == "full"):
        result_shape = len(in1) + 1
        in1 = np.pad(in1, (m - 1, m - 1), mode='constant')
        
    if(mode == "valid"):
        result_shape = n - m + 1
        # for k in range(result_shape):
        #     slider = in1[k:k+m]
        #     result.append(np.sum(slider * in2))
    for row in range(result_shape):
            for col in range(result_shape):
                slider = in1[ row:row+m,col:col+m,]
                result.append(np.sum(slider * in2))
    
    return np.array(result).reshape(result_shape, result_shape).astype(int)

In [114]:
main()

[[0 1 2]
 [0 5 7]
 [0 4 5]]
------
[[0 1 2]
 [0 5 7]
 [0 4 5]]
[[5]]
------
[[5]]
[]
------
[[5 7]
 [4 5]]
